apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app that displays time
  annotations:
    github.com/project-slug: julianomontini/idp-python-app
spec:
  type: service
  lifecycle: experimental
  owner: development